mjcf_list:
  - xml/franka_emika_panda/panda.xml

renderer_list:
  - madrona

rasterizer_list:
  - true

batch_size_list:
  - 1024
  - 2048

resolution_list:
  #square:
    - [128, 128]
    - [256, 256]
  
  #four_three:
  
  #sixteen_nine:

comparison_sets:
