mjcf_list:
  - xml/franka_emika_panda/panda.xml

renderer_list:
  - madrona

rasterizer_list:
  - true

batch_size_list:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192

resolution_lists:
  #square:
    - [128, 128]
    - [256, 256]
  
  #four_three:
  
  #sixteen_nine: